### ISSUE TITLE
How to embed?

### ISSUE THREAD

**Issue by enesa21** [cjwd/user-database-airtable-tut#20]
How would I go about embedding it onto an existing site? (for example a weebly site) @cjwd

**Comment by cjwd** [comment]
Hi @enesa21 this tutorial is for building a stand alone application using the NodeJs framework espressjs.
If you need something for weebly you could use write your own Javascript based on the ideas presented in this tutorial. The logic remains the same but the structure of the application would be different.
there are some vanilla Javascript examples on glitch.com that could provide you with some scaffolding code.
